routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'indexController@home')->name('home');

    Route::resource('profile', 'ProfileController');
    Route::resource('follow', 'FollowController');

    Route::resource('post', 'PostController');
});

//Route Resource example
// Route::get('/example', 'ExampleController@index')->name('example.index');
// Route::get('/example/create', 'ExampleController@create')->name('example.create');
// Route::post('/example', 'ExampleController@store')->name('example.store');
// Route::get('/example/{example_id}', 'ExampleController@show')->name('example.show');
// Route::get('/example/{example_id}/edit', 'ExampleController@edit')->name('example.edit');
// Route::put('/example/{example_id}', 'ExampleController@update')->name('example.update');
// Route::delete('/example/{example_id}', 'ExampleController@destroy')->name('example.destroy');


// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/master', function () {
//     return view('layout.master');
// });



// Route::get('/show', function () {
//     return view('profile.show');
// });

// Route::get('/edit', function () {
//     return view('profile.edit');
// });



//dikomen krn sudah pakai route bawaan Auth
// Route::get('/register', function () {
//     return view('pages.register');
// });

// Route::get('/login', function () {
//     return view('pages.login');
// });

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Social Media</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('quixlab-master/images/favicon.png')}}">
    <!-- Font Awesome -->
    <!-- <link rel="stylesheet" href="{{asset('quixlab-master/icons/font-awesome/css/font-awesome.min.css')}}"> -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <!-- Custom Stylesheet -->
    <link href="{{asset('quixlab-master/css/style.css')}}" rel="stylesheet">
    <!-- select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />


    @stack('style')
</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!-- Navbar -->
        @include('layout.nav')
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        @include('layout.sidebar')
        <!-- /.sidebar -->

        <!-- Content Body start -->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">@yield('title')</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                @yield('content')

            </div>
            <!-- #/ container -->
        </div>
        <!-- Content Body end -->


        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js"></script>
    <script src="{{asset('js/customOwn.js')}}"></script>

    <script src="{{asset('quixlab-master/plugins/common/common.min.js')}}"></script>
    <script src="{{asset('quixlab-master/js/custom.min.js')}}"></script>
    <script src="{{asset('quixlab-master/js/settings.js')}}"></script>
    <script src="{{asset('quixlab-master/js/gleek.js')}}"></script>
    <script src="{{asset('quixlab-master/js/styleSwitcher.js')}}"></script>
    <!-- select2 -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>

</html>

resources/views/layout/nav.blade.php
 <!--**********************************
            Nav header start
        ***********************************-->
 <div class="nav-header">
     <div class="brand-logo">
         <a href="route('home)">
             <b class="logo-abbr"><img src="{{asset('quixlab-master/images/s_trans.png')}}" alt="ccc"> </b>
             <span class="logo-compact"><img src="{{asset('quixlab-master/images/s_trans.png')}}" alt="aaa"></span>
             <span class="brand-title">
                 <img src="{{asset('quixlab-master/images/sosmedku_trans.png')}}" alt="ddd" class="img-thumbnail" style="background-color:transparent">
             </span>
         </a>
     </div>
 </div>
 <!--**********************************
            Nav header end
        ***********************************-->

 <!--**********************************
            Header start
        ***********************************-->
 <div class="header">
     <div class="header-content clearfix">

         <div class="nav-control">
             <div class="hamburger">
                 <span class="toggle-icon"><i class="icon-menu"></i></span>
             </div>
         </div>
         <div class="header-left">
             <div class="row mt-4">
                 <div class="col">
                     <select class="form-control" id="su" style="width: 200%;">
                         <option></option>
                         @foreach ($show_all_users_everywhere as $data)
                         <option value="{{route('profile.show',$data->id)}}">{{$data->name}}</option>
                         @endforeach
                     </select>
                 </div>
             </div>
         </div>

         <div class="header-right">
             <ul class="clearfix">
                 <li class="icons dropdown"><a href="javascript:void(0)" data-toggle="dropdown">
                         <i class="mdi mdi-email-outline"></i>
                         <span class="badge gradient-1 badge-pill badge-primary">3</span>
                     </a>
                     <div class="drop-down animated fadeIn dropdown-menu">
                         <div class="dropdown-content-heading d-flex justify-content-between">
                             <span class="">3 New Messages</span>

                         </div>
                     </div>

                 <li class="icons dropdown"><a href="javascript:void(0)" data-toggle="dropdown">
                         <i class="mdi mdi-bell-outline"></i>
                         <span class="badge badge-pill gradient-2 badge-primary">2</span>
                     </a>
                     <div class="drop-down animated fadeIn dropdown-menu dropdown-notfication">
                         <div class="dropdown-content-heading d-flex justify-content-between">
                             <span class="">2 New Notifications</span>

                         </div>
                     </div>
                 </li>

                 <li class="icons dropdown">
                     <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                         <span class="activity active"></span>
                         @auth
                         @isset (auth()->user()->profile->image_profile)
                         <img src="{{asset('images/'.auth()->user()->profile->image_profile)}}" height="40" width="40" alt="">
                         @else
                         <img src="{{asset('images/no_image_profile.png')}}" height="40" width="40" alt="">
                         @endisset
                         @endauth
                         @guest
                         <img src="{{asset('images/guest.png')}}" height="40" width="40" alt="">
                         @endguest
                     </div>
                     <div class="drop-down dropdown-profile dropdown-menu">
                         <div class="dropdown-content-body">
                             <ul>
                                 <li>
                                     <a href="{{route('profile.index')}}"><i class="icon-user"></i> <span>Profile</span></a>
                                 </li>
                                 <hr class="my-2">
                                 @guest
                                 <li>
                                     <a href="{{route('login')}}"><i class="icon-key"></i> <span>Login</span></a>
                                 </li>
                                 @endguest
                                 @auth
                                 <li>
                                     <a href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                                         <i class="icon-logout"></i>
                                         <span>
                                             Logout
                                         </span>
                                     </a>
                                     <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                         @csrf
                                     </form>
                                 </li>
                                 @endauth
                             </ul>
                         </div>
                     </div>
                 </li>
             </ul>
         </div>
     </div>
 </div>
 <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

resources/views/layout/sidebar.blade.php
<div class="nk-sidebar">
    <div class="nk-nav-scroll">

        <ul class="metismenu" id="menu">
            <li>
                <a href="{{ route('profile.index') }}" aria-expanded="false">
                    <span class="user-img c-pointer position-relative">
                        @auth
                        @isset (auth()->user()->profile->image_profile)
                        <img src="{{asset('images/'.auth()->user()->profile->image_profile)}}" height="40" width="40" alt="">
                        <span class="nav-text">{{strtoupper(explode(' ',trim(auth()->user()->profile->name))['0'])}}</span>
                        @else
                        <img src="{{asset('images/no_image_profile.png')}}" height="40" width="40" alt="">
                        <span class="nav-text">{{strtoupper(explode(' ',trim(auth()->user()->name))['0'])}}</span>
                        @endisset
                        @endauth
                        @guest
                        <img src="{{asset('images/guest.png')}}" height="40" width="40" alt="">
                        <span class="nav-text">Guest</span>
                        @endguest
                    </span>
                </a>
            </li>
        </ul>
        <ul class="metismenu" id="menu">
            <li>
                <a href="{{ route('home') }}" aria-expanded="false">
                    <i class="icon-home menu-icon"></i><span class="nav-text">Home</span>
                </a>
            </li>

            @auth
            <li>
                <a href="{{ route('profile.index') }}" aria-expanded="false">
                    <i class="icon-settings menu-icon"></i><span class="nav-text">Profile</span>
                </a>
            </li>
            <li>
                <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="icon-logout menu-icon" aria-hidden="true"></i>
                    <span class="nav-text">
                        Logout
                    </span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
            @endauth

            @guest
            <li>
                <a href="{{ route('login') }}" aria-expanded="false">
                    <i class="icon-login menu-icon"></i><span class="nav-text">Login</span>
                </a>
            </li>
            @endguest
        </ul>
    </div>
</div>